version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 12.x
      java: corretto11
    commands:
      - node -v
      - npm -v
      - npm i -g npm
  pre_build:
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_SRC_DIR
      - env
      - ifconfig
      - node -v
      - aws --version
      - aws dynamodb batch-write-item --request-items file://dynamoDB/prepped.json

  build:
    commands:
      - cd cypress
      - npm install
      - npm test
      - cd ../karate
      - ./gradlew test --info

  post_build:
    commands:
      - cd ..
      - if [ -d "build/karate-reports" ]; then aws s3 cp build/karate-reports s3://bibliotekstjenester-test-reports/karate/$CODEBUILD_BUILD_NUMBER --recursive; fi
      - if [ -d "karate/build/karate-reports" ]; then aws s3 cp karate/build/karate-reports s3://bibliotekstjenester-test-reports/karate/$CODEBUILD_BUILD_NUMBER --recursive; fi
      - if [ -d "cypress/cypress/screenshots" ]; then aws s3 cp cypress/cypress/screenshots s3://bibliotekstjenester-test-reports/cypress/$CODEBUILD_BUILD_NUMBER/screenshots --recursive; fi
      - if [ -d "cypress/cypress/videos" ]; then aws s3 cp cypress/cypress/videos s3://bibliotekstjenester-test-reports/cypress/$CODEBUILD_BUILD_NUMBER/videos --recursive; fi
      - aws dynamodb batch-write-item --request-items file://dynamoDB/delete_items.json
      - aws s3 rm s3://contents-backend-s3-storage-test/files/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: $(date +%Y-%m-%d)
